name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Update rustup
        run: rustup self update

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup update stable
          rustup default stable

      - name: Install components
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: Check format files
        run: cargo fmt -- --check

      - name: Check clippy
        run: cargo clippy --all-targets --all-features --all

      - name: Run tests
        env:
          APP_SECRET_KEY: NextChatORG
          DATABASE_URL: postgres://postgres:password@localhost/nextchat
        run: cargo test --workspace
